def durice():
    durice_list = [
        ' Vivillon',
        ' Furret',
        ' Cubchoo',
        ' Beartic',
        ' Mightyena',
        ' Wevile',
        ' Braviary',
        ' Swinub',
        ' Mamoswine',
        ' Skarmory',
        ' Sandslash',
        ' Abomasnow',
        ' Vulpix',
        ' Delibird',
        ' Snom',
        ' Frosmoth',
        ' Crabominable',
        ' Snorunt',
        ' Glalie',
        ' Froslass',
        ' Jynx',
        ' Spheal',
        ' Piplup',
        ' Vanilluxe',
        ' Avalugg',
        ' Dewgong',
        ' Aurorus',
        ' Glaceon',
        ' Suicune',
        ' Crobat',
        ' Joltik',
        ' Geodude',
        ' Carbink',
        ' Gengar',
        ' Noibat',
        ' Pumpkaboo',
        ' Croagunk',
        ' Drifloon',
        ' Clefairy',
        ' Sableye',
        ' Rampardos',
        ' Hydreigon',
        ' Goodra',
        ' Marwile',
        ' Jolteon',
        ' Diancie',
        ' Steelix'

    ]

    print('DURICE ISLAND:')

    for x in durice_list:
        print(x)
