def maricopia():
    maricopia_list = [
        ' Vivillon',
        ' Magikarp',
        ' Pikachu',
        ' Wingull',
        ' Exeggutor',
        ' Crabrawler',
        ' Drifblim',
        ' Zangoose',
        ' Seviper',
        ' Bellossom',
        ' Inkay',
        ' Pyukumuku',
        ' Machamp',
        ' Stunfisk',
        ' Octillery',
        ' Corsola',
        ' Finneon',
        ' Clampearl',
        ' Primarina',
        ' Raichu',
        ' Sandygast',
        ' Sharpedo',
        ' Squirtle',
        ' Blastoise',
        ' Lapras',
        ' Mantine',
        ' Pelipper',
        ' Wailord',
        ' Mareanie',
        ' Vaporeon',
        ' Manaphy',
        ' Luvdisc',
        ' Alomomola',
        ' Wailmer',
        ' Cradily',
        ' Lumineon',
        ' Qwilfish',
        ' Clawitzer',
        ' Tentacruel',
        ' Chinchou',
        ' Lanturn',
        ' Starmie',
        ' Frillish',
        ' Golisopod',
        ' Lugia',
        ' Wishiwashi'

    ]

    print('MARICOPIA ISLAND:')

    for x in maricopia_list:
        print(x)
